ext {
    mapstructVersion='1.6.3'
    junitVersion = '5.11.4'
}

dependencies {

    implementation 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'

    implementation "org.mapstruct:mapstruct:${mapstructVersion}"
    implementation "org.mapstruct:mapstruct-processor:${mapstructVersion}"
    annotationProcessor "org.mapstruct:mapstruct-processor:${mapstructVersion}"

    implementation 'org.springframework.boot:spring-boot-starter-security'

    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'

    implementation 'ru.clevertec:spring-boot-aop-logging-starter:0.0.1'
    implementation 'ru.clevertec:spring-boot-exception-handling-starter:0.0.1'

}

